name: ZAP Scan on WebGoat

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan WebGoat with ZAP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git credentials (for pushing scan results)
        run: |
          git config --global user.name 'swapmaurya'
          git config --global user.email 'swapmaurya20@gmail.com'

      - name: Pull WebGoat Docker image
        run: docker pull webgoat/webgoat

      - name: Run WebGoat container
        run: |
          docker run -p 127.0.0.1:8080:8080 -p 127.0.0.1:9090:9090 -e webgoat/webgoat
          sleep 10

      - name: Run ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://127.0.0.1:8080/WebGoat'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          cmd_options: '-a'
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_issue_writing: false

      - name: Copy ZAP results to output folder
        run: |
          mkdir -p output
          cp report_html.html output/

      - name: Commit and Push ZAP reports
        run: |
          git add output/
          git commit -m "Add ZAP scan reports for WebGoat [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
