name: KDT CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh
          export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
          export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
          
      - name: Check Scanner and Project
        run: |
          export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
          export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
          kdt list scanners

      # - name: Run a CS scan
      #   run: |
      #     export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
      #     export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
      #     kdt scan \
      #       -p ${{ github.event.repository.name }} \
      #       -t dependencycheck \
      #       -b main
  
      - name: Run a SAST scan
        run: |
          export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
          export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
          kdt scan \
            -p ${{ github.event.repository.name }} \
            -t semgrep \
            -b main
          
      # - name: Run a SAST scan
      #   run: |
      #     export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
      #     export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
      #     kdt scan \
      #       -p ${{ github.event.repository.name }} \
      #       -t findsecbugs \
      #       -b main

      # - name: Run a CS scan
      #   run: |
      #     export KONDUKTO_HOST=${{ secrets.KONDUKTO_HOST }}
      #     export KONDUKTO_TOKEN=${{ secrets.KONDUKTO_TOKEN }}
      #     kdt scan \
      #       -p ${{ github.event.repository.name }} \
      #       -t trivy \
      #       --image=webgoat:latest \
      #       -b main
